;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/KhaosTitanium/Content/Localization/KhaosTitanium
DestinationPath=Saved/Tolgee/Temp/KhaosTitanium
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=de
CulturesToGenerate=ja
CulturesToGenerate=ko
CulturesToGenerate=pl
CulturesToGenerate=ru
CulturesToGenerate=zh
ManifestName=KhaosTitanium.manifest
ArchiveName=KhaosTitanium.archive
PortableObjectName=KhaosTitanium.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bExportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Crowdin
ShouldPersistCommentsOnExport=false
ShouldAddSourceLocationsAsComments=true

