;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Saved/Tolgee/Temp/KhaosTitanium
DestinationPath=Mods/GameFeatures/KhaosTitanium/Content/Localization/KhaosTitanium
NativeCulture=en
CulturesToGenerate=de
CulturesToGenerate=en
CulturesToGenerate=ja
CulturesToGenerate=ko
CulturesToGenerate=pl
CulturesToGenerate=ru
CulturesToGenerate=zh
ManifestName=KhaosTitanium.manifest
ArchiveName=KhaosTitanium.archive
PortableObjectName=KhaosTitanium.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bImportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Crowdin

