;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Mods/GameFeatures/KhaosTitanium/Content/Localization/KhaosTitanium
DestinationPath=Mods/GameFeatures/KhaosTitanium/Content/Localization/KhaosTitanium
ManifestName=KhaosTitanium.manifest
ArchiveName=KhaosTitanium.archive
ResourceName=KhaosTitanium.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=en
CulturesToGenerate=de
CulturesToGenerate=en
CulturesToGenerate=ja
CulturesToGenerate=ko
CulturesToGenerate=pl
CulturesToGenerate=ru
CulturesToGenerate=zh

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

